### ISSUE TITLE
Report on This week in GNOME

### ISSUE THREAD

**Issue by CleoMenezesJr** [dlippok/photometric-viewer#7]
Hi, sorry to open an issue for this. But I found this app on Flathub and I think it would be really cool to report this app on This week in GNOME. It would gain a lot of visibility.
https://matrix.to/#/#thisweek:gnome.org

**Comment by dlippok** [comment]
@CleoMenezesJr Thanks a lot for making me aware of this channel. I would like to release the 1.0 version and run tests with different types of photometric files before I announce this application to a broader audience though. 

By the way, is there any process for announcing a non-core application in the chat? Should I tag the bot and present shortly the application and its features?
