### ISSUE TITLE
Improve branding

### ISSUE THREAD

**Issue by bragefuglseth** [dlippok/photometric-viewer#78]
Hi there! Photometric Viewer currently has a [descriptive name](https://developer.gnome.org/hig/guidelines/app-naming.html) and an icon that follows [GNOME's app icon style](https://developer.gnome.org/hig/guidelines/app-icons.html), which is great! I have some suggestions to improve the branding even further:

- Redesign the app icon to drop the symbolic usage and avoid using transparency. I can help with this if you want me to. You can reach out to us in the [GNOME App Icon Design group](https://matrix.to/#/#appicondesign:gnome.org) on Matrix for guidance or answers to any questions you might have.
- Simplify the name. "Photometric Viewer" works well, except for the length. What about shortening it to "Photometry"? I assume that you're pretty knowledgeable about this field, so if you have any other fitting names that follow the guidelines, they could also work just as well. The app ID can stay identical, we can just change the name in the locations where it's displayed.

You don't *need* to do any of these, of course, but it would be nice to make your app fit even better into the GNOME ecosystem! :grin:

**Comment by dlippok** [comment]
Hi @bragefuglseth. Thanks a lot for the suggestions. In fact I was already thinking about changing the icon as the translarency doesn't work well in some contexts. 

Regarding the naming, I like the idea of calling it just "Photometry" but would need think about it as the term is way broader than what the application does.

**Comment by bragefuglseth** [comment]
Some name suggestions based on articles about the topic:

- Luminous
- Luminaire
- Lantern
- Lampshade

To be memorable and unique, the app name shouldn't just be a generic description of exactly what the app does. If it's a physical noun (like Lantern or Lampshade), it can also translate into a great app icon.

**Comment by dlippok** [comment]
# Option 1: Lightbulb

![lightbulb](https://github.com/dlippok/photometric-viewer/assets/8083560/124ad594-c056-4f17-86af-3474bcbf436a) ![lightbulb-symbolic](https://github.com/dlippok/photometric-viewer/assets/8083560/594a1cdf-0ef2-4a70-868b-da05ff000c7c)

[lightbulb.zip](https://github.com/dlippok/photometric-viewer/files/12794889/lightbulb.zip)
